'use client';
import { Children, cloneElement, isValidElement, useEffect, useState, type ReactNode, type ReactElement } from 'react';
import { FileText, X, GripVertical, ArrowLeft, ArrowRight } from 'lucide-react';

function InteractionSparkline({counts}: {counts:number[]}) {
  const max=Math.max(1,...counts);const points=counts.map((value,i)=>[2+i*100/(counts.length-1),34-value/max*30]);
  let path=`M ${points[0][0]},${points[0][1]}`;
  for(let i=0;i<points.length-1;i++){const p0=points[Math.max(0,i-1)],p1=points[i],p2=points[i+1],p3=points[Math.min(points.length-1,i+2)];path+=` C ${p1[0]+(p2[0]-p0[0])/6},${p1[1]+(p2[1]-p0[1])/6} ${p2[0]-(p3[0]-p1[0])/6},${p2[1]-(p3[1]-p1[1])/6} ${p2[0]},${p2[1]}`;}
  return <svg className="app-sparkline" viewBox="0 0 104 36" role="img" aria-label="Illustrative monthly interaction activity"><path d={`${path} L 102,36 L 2,36 Z`} fill="#007aff" fillOpacity=".12"/><path d={path} fill="none" stroke="#007aff" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>;
}

const initialOrder = ['up-next','this-month','tips','recommendations','activity','quotes','renewals','popular','recent'];
const sourceOrder = ['up-next','this-month','recommendations','activity','quotes','tips','renewals','popular','recent'];
function ReorderableDashboard({children}: {children: ReactNode}) {
  const [order,setOrder] = useState(initialOrder);
  const [dragged,setDragged] = useState<string|null>(null);
  const [announcement,setAnnouncement] = useState('');
  useEffect(()=>{try {const saved: unknown = JSON.parse(localStorage.getItem('nearfield-marketing-card-order') || 'null');if(Array.isArray(saved)){const valid=[...new Set(saved.filter((id): id is string=>typeof id==='string'&&initialOrder.includes(id)))];setOrder([...valid,...initialOrder.filter(id=>!valid.includes(id))]);}}catch{}},[]);
  function move(id:string,target:string) {if(id===target)return;const next=order.filter(item=>item!==id);next.splice(order.indexOf(target),0,id);setOrder(next);setAnnouncement(`Card moved to position ${next.indexOf(id)+1}.`);try{localStorage.setItem('nearfield-marketing-card-order',JSON.stringify(next));}catch{}}
  const cards=Children.toArray(children);
  return <><div className="dashboard-reorder-toolbar"><span>Reorder this preview</span><button onClick={()=>{setOrder(initialOrder);setAnnouncement('Default card order restored.');try{localStorage.removeItem('nearfield-marketing-card-order');}catch{}}}>Reset Order</button></div><span className="sr-only" aria-live="polite">{announcement}</span><div className="dashboard-grid reorderable-grid">{order.map((id,index)=>{const card=cards[sourceOrder.indexOf(id)];if(!isValidElement(card))return null;const element=card as ReactElement<{className:string;children:ReactNode}>;return cloneElement(element,{key:id,children:<><div className="card-order-controls"><span draggable onDragStart={event=>{setDragged(id);event.dataTransfer.setData('text/plain',id);event.dataTransfer.effectAllowed='move';}} onDragEnd={()=>setDragged(null)} aria-label="Drag card"><GripVertical size={16}/></span><button aria-label={`Move ${id.replaceAll('-',' ')} earlier`} disabled={index===0} onClick={()=>move(id,order[index-1])}><ArrowLeft size={14}/></button><button aria-label={`Move ${id.replaceAll('-',' ')} later`} disabled={index===order.length-1} onClick={()=>move(id,order[index+1])}><ArrowRight size={14}/></button></div>{element.props.children}</>,...{onDragOver:(event:React.DragEvent)=>{if(dragged)event.preventDefault();},onDrop:(event:React.DragEvent)=>{event.preventDefault();if(dragged)move(dragged,id);setDragged(null);}}});})}</div></>;
}

export default function Dashboard() {
  const [showSignal, setShowSignal] = useState(true);
  return <div className="dashboard-canvas"><h2>Good to see you.</h2>{showSignal && <div className="dashboard-signal-banner"><img className="signal-banner-icon" src="/signal.png" width="36" height="36" alt="Signal"/><div><strong>Add Signal to Nearfield</strong><p>Read conversations stored on this Mac. Nothing is sent to Nearfield servers. Shared only with devices you pair.</p></div><a href="#signal" title="Learn about enabling Signal in the Mac app">Enable Signal</a><button onClick={()=>setShowSignal(false)} aria-label="Dismiss Signal preview banner"><X size={14}/></button></div>}<ReorderableDashboard>
    <article className="dashboard-card"><h3>Up Next</h3>{[['9:30 AM','Team check-in','Sep 11'],['10:00 AM','Design review','Sep 11']].map(([time,title,date])=><div className="agenda-preview" key={time}><span>{date}<small>{time}</small></span><div><strong>{title}</strong><p>Project updates and next steps</p></div><span className="preview-link">View Source</span></div>)}<div className="meeting-preview"><span>In Your Next Meeting</span><strong>Project catch-up</strong><p>Fri, Sep 11 · 10:30 AM</p><p>With <span className="tiny-avatar">AM</span> Alex Morgan</p><p>Studio North</p><span className="preview-link">View Source</span></div></article>
    <article className="dashboard-card"><h3>This Month</h3><p>28 events in September</p><p className="milestone-legend">Quote · 30d · Renewal · Start</p><div className="month-preview" role="img" aria-label="Illustrative September calendar: September 11 is today; dots mark business milestones">{Array.from({length:35},(_,i)=><span key={i} className={i===12?'today-cell':''} style={{backgroundColor:`rgba(0,122,255,${i<2||i>31?.04:.12+((i*7)%5)*.15})`}}>{i===12?'Today':''}{[7,18,24].includes(i)&&<i/>}</span>)}</div><div className="busiest-preview"><strong>Busiest Day</strong><span>Wednesday, September 16 · 4 events</span></div><p className="month-events-heading">Events on September 16</p>{[['9:00 AM','Project kickoff'],['11:00 AM','Design review'],['1:30 PM','Team check-in'],['3:00 PM','Client catch-up']].map(([time,title])=><div className="month-event" key={time}><span>{time}</span><strong>{title}</strong><span className="preview-link">View Source</span></div>)}</article>
    <article className="dashboard-card"><h3>Who to Talk To</h3>{[{name:'Sam Rivera',initials:'SR',reason:'Active in shared Signal conversations, most recently Sep 10, 2026. Consider checking in.',counts:[2,4,1,6,9,12]},{name:'Taylor Chen',initials:'TC',reason:'Listed for Design Workshop on Sep 16, 2026. Consider checking in before the event.',counts:null},{name:'Alex Morgan',initials:'AM',reason:'18 supported interactions, most recently Sep 9, 2026. Keep the conversation moving.',counts:[8,5,6,2,4,7]}].map(person=><div className="recommendation-preview" key={person.name}><span className="tiny-avatar">{person.initials}</span><div><strong>{person.name}</strong><p>{person.reason}</p></div>{person.counts?<InteractionSparkline counts={person.counts}/>:<span className="upcoming-label">Upcoming</span>}<span className="preview-link">View Source</span><span className="preview-dismiss">Dismiss</span></div>)}</article>
    <article className="dashboard-card"><h3>Weekly Activity</h3><p className="chart-caption">6,337 records across your full archive · Wednesday carries 25% of activity</p><div className="activity-preview" role="img" aria-label="Illustrative weekly activity: Wednesday is the busiest day">{[38,65,94,59,76,25,18].map((height,index)=><div key={index}><div className="activity-track"><i style={{height:`${height}%`}}/></div><span>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][index]}</span></div>)}</div><div className="activity-legend"><span/> Messages · Events · Other</div></article>
    <article className="dashboard-card"><h3>Open Quotes and Proposals</h3><p>PROPOSAL · Aug 19, 2026</p><strong>Studio North</strong><p>No matching contract found</p><div className="quote-document"><span>Talked with<strong>Alex Morgan</strong><small>alex@studio-north.example</small></span><span>Follow up with Alex Morgan<small>Sep 18, 2026</small><span className="preview-link">Draft Email</span></span></div><div className="quote-document"><FileText size={19}/><span>Proposal<strong>Website Proposal</strong><small>Mail · Aug 19, 2026</small></span><span className="preview-link">View Proposal</span></div></article>
    <article className="dashboard-card tip-preview"><h3>Tip Inbox</h3><p>Hush Line · 4 <span className="preview-link">View All Tips</span></p>{['A question about the project timeline.','Details shared for your review.','An update on a previous submission.','A request for a follow-up.'].map((text,i)=><div className="tip-item" key={text}><strong>{i===2?'New Hush Line Conversation Activity':'New Hush Line Message Received'}</strong><p>{text}</p><div><span>{i<2?'Sep 11, 2026':'Sep 10, 2026'}</span><span className="preview-link">View Source</span></div></div>)}</article>
    <article className="dashboard-card renewal-preview"><h3>Upcoming Renewals</h3><strong>Beacon Studio</strong><p>Annual renewal · Maintenance Agreement</p><p>“This agreement renews annually on October 1.”</p><p>Oct 1, 2026</p><span className="preview-link">View Source</span></article>
    <article className="dashboard-card popular-preview"><h3>Popular Contacts</h3>{['Sam Rivera','Taylor Chen','Alex Morgan'].map(name=><div className="compact-record" key={name}><span className="tiny-avatar">{name.split(' ').map(n=>n[0]).join('')}</span><div><strong>{name}</strong><p>12 sources</p></div><span className="preview-dismiss">38 mentions</span></div>)}</article>
    <article className="dashboard-card recent-preview"><h3>Recent Messages</h3>{[['Sam Rivera','Project check-in','Signal'],['Taylor Chen','See you at the workshop','Messages'],['Alex Morgan','Re: Website proposal','Mail']].map(([name,subject,source])=><div className="compact-record" key={name}><div><strong>{name}</strong><p>{subject}</p></div><span className="record-source">{source}</span></div>)}</article>
  </ReorderableDashboard></div>
}
