import Dashboard from './dashboard';
import ProductPreview from './product-preview';
import CardFeatures from './card-features';
import { ArrowDown, ArrowUpRight, LockKeyhole, Mail, CalendarDays, FileText, MessageCircle, ContactRound, ShieldCheck, Code2 } from 'lucide-react';
function Brand(){return <a className="brand" href="#top" aria-label="Nearfield home"><img src={`${process.env.NEXT_PUBLIC_BASE_PATH || ''}\/nearfield.png`} alt="" width="38" height="38"/>Nearfield</a>}
export default function Home(){return <><a className="skip" href="#main">Skip to content</a><header id="top"><div className="nav"><Brand/><nav aria-label="Main navigation"><a href="#product">The product</a><a href="#signal">Signal</a><a href="#tip-inbox">Hush Line</a><a href="#privacy">Your data</a><a className="nav-cta" href="#availability">In development <ArrowUpRight size={16}/></a></nav></div></header><main id="main">
<section className="hero wrap"><h1>The missing relationship<br className="desktop-break"/> layer for <span>your Mac.</span></h1><p className="hero-description">Who to talk to. What’s next. What needs a follow-up.<br/>Your local data, brought together in one dashboard.</p><div className="actions"><a href="#product" className="button primary">See your day, connected <ArrowDown size={18}/></a></div><p className="promise">No cloud. No tracking. No fees.</p>
<ProductPreview><div className="product-window"><div className="window-bar"><div className="traffic" aria-hidden="true"><i/><i/><i/></div><span>Nearfield</span><span className="local-label"><LockKeyhole size={12}/> Local archive</span></div><div className="app-layout"><aside className="app-sidebar" aria-label="Illustrative app navigation"><div className="mini-brand"><img src={`${process.env.NEXT_PUBLIC_BASE_PATH || ''}\/nearfield.png`} alt="" width="27" height="27"/>Nearfield</div>{['Home','People','Companies','Documents','Network','Locations','Events','Messages','Notes'].map(t=><span className={t==='Home'?'selected':''} key={t}>{t}</span>)}<span className="sidebar-bottom">Settings</span></aside><Dashboard/></div></div></ProductPreview></section>
<section className="sources wrap" aria-label="Local data sources"><p>The data already on your Mac, finally working together.</p><div>{[{Icon:Mail,label:'Mail'},{Icon:MessageCircle,label:'Messages'},{Icon:MessageCircle,label:'Signal'},{Icon:CalendarDays,label:'Calendar'},{Icon:ContactRound,label:'Contacts'},{Icon:FileText,label:'Notes & files'}].map(({Icon,label})=><span key={label}><Icon size={23}/>{label}</span>)}</div></section>
<CardFeatures/>
<section className="signal-section wrap" id="signal"><div><h2>Your conversations.<br/><span>Part of the bigger picture.</span></h2><p>Add conversations stored in Signal Desktop to Nearfield. See them alongside email and Messages, and let recent activity inform who to talk to.</p><p className="signal-details">An optional, read-only integration in preview. Requires Signal Desktop on your Mac and your approval to access its encryption key through macOS Keychain. Disappearing and view-once messages are excluded.</p></div><div className="signal-example"><div className="signal-example-heading"><img src={`${process.env.NEXT_PUBLIC_BASE_PATH || ''}\/signal.png`} width="36" height="36" alt="Signal"/><strong>Signal in Nearfield</strong><span>✓ Connected</span></div><div className="signal-record"><span className="tiny-avatar">JS</span><div><strong>Jerry Seinfeld</strong><p>Active in shared Signal conversations, most recently this week. Consider checking in.</p><span className="record-source">Signal · Source-backed context</span></div></div><div className="signal-assurances"><p><ShieldCheck size={18}/> No messages sent or changed in Signal.</p><p><LockKeyhole size={18}/> No upload to Nearfield servers.</p></div><p className="signal-footnote">Imported text becomes part of your local archive and is available to devices you pair. Manage or disconnect access in Settings.</p></div></section>


<section className="privacy wrap" id="privacy"><div className="privacy-heading"><div className="shield"><ShieldCheck size={40} strokeWidth={1.3}/></div><h2>Relationships already on your computer,<br/><span>not someone else's cloud.</span></h2><p>Relationship intelligence shouldn’t mean handing over your life.<br/>Nearfield’s archive lives on your Mac, under your control.</p></div><div className="principles"><article><LockKeyhole/><h3>Local by design.</h3><p>Your data never leaves your computer.</p></article><article><ShieldCheck/><h3>No telemetry.</h3><p>No tracking your activity.</p></article><article><Code2/><h3>Open-source code.</h3><p>Don't trust us, verify our code.</p></article></div><p className="privacy-note">Local doesn’t mean every feature is offline. Map imagery uses Apple Maps. Optional remote access uses a secure connection via the Tor Network to your Mac.</p></section>
<section className="closing wrap" id="availability"><img src={`${process.env.NEXT_PUBLIC_BASE_PATH || ''}\/nearfield.png`} alt="Nearfield connected-node N icon" width="92" height="92"/><h2>A little closer<br/>to the bigger picture.</h2><p>Nearfield is in active development.<br/>Public downloads and App Store availability are not here yet.</p><a href="#product" className="button primary">Explore the product <ArrowUpRight size={18}/></a></section></main><footer className="wrap"><Brand/><p>A product of Hush Line, a 501(c)(3) non-profit in the United States.</p><a href="#top">Back to top ↑</a></footer></>}
